# UOC Programacio Avançada per ciencia de dades 
# ATENCIO: Contenidor no oficial. La UOC no suporta aquest contenidor.

version: "3.2"

services:
 datasci:
   container_name: UOC_AdvPython
   build:
    context: .
    dockerfile: ./uoc-scripts/Dockerfile
   command: jupyter-notebook --no-browser --ip="0.0.0.0" --port=8888 --notebook-dir=/home/datasci/ --NotebookApp.token='' --NotebookApp.password=''
   volumes:
    - ./:/home/datasci/
   network_mode: host
   restart: on-failure
